/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    articles: Article;
    categories: Category;
    media: Media;
    users: User;
    themes: Theme;
    analytics: Analytics;
    reels: Reel;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    themes: ThemesSelect<false> | ThemesSelect<true>;
    analytics: AnalyticsSelect<false> | AnalyticsSelect<true>;
    reels: ReelsSelect<false> | ReelsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'app-layout': AppLayout;
  };
  globalsSelect: {
    'app-layout': AppLayoutSelect<false> | AppLayoutSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  /**
   * Article title (max 200 characters)
   */
  title: string;
  content: {
    [k: string]: unknown;
  }[];
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Como este artigo deve aparecer nas listagens.
   */
  cardType: 'card_normal' | 'card_detailed' | 'title_only' | 'thumbnail_only';
  /**
   * Select a theme for this article
   */
  theme?: (number | null) | Theme;
  /**
   * Mark as featured article (appears on top)
   */
  featured?: boolean | null;
  /**
   * Main featured image for the article
   */
  featuredImage?: (number | null) | Media;
  /**
   * Short description for previews (max 300 characters)
   */
  description?: string | null;
  /**
   * Select article authors (multiple selection allowed)
   */
  authors?: (number | User)[] | null;
  /**
   * Select categories for this article
   */
  categories?: (number | Category)[] | null;
  /**
   * Current publication status
   */
  status: 'draft' | 'pending_approval' | 'published' | 'rejected';
  /**
   * Publication date
   */
  publishedAt?: string | null;
  /**
   * Article creator
   */
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Gerencie temas, cores, tipografia e estilos visuais da aplicação
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes".
 */
export interface Theme {
  id: number;
  /**
   * Nome do tema (ex: "Campus Padrão", "Modo Escuro", "Alto Contraste")
   */
  name: string;
  /**
   * Identificador amigável para URL (API)
   */
  slug: string;
  /**
   * Descrição deste tema e quando usá-lo
   */
  description?: string | null;
  /**
   * Ativar/desativar este tema
   */
  isActive?: boolean | null;
  /**
   * Definir como tema padrão (apenas um deve ser padrão)
   */
  isDefault?: boolean | null;
  colors: {
    primary: {
      /**
       * Cor principal da marca (formato hex: #1976d2)
       */
      main: string;
      /**
       * Variante mais clara (auto-gerada se vazia)
       */
      light?: string | null;
      /**
       * Variante mais escura (auto-gerada se vazia)
       */
      dark?: string | null;
      /**
       * Cor do texto sobre fundo primário
       */
      contrast?: string | null;
    };
    secondary: {
      /**
       * Cor secundária da marca
       */
      main: string;
      /**
       * Variante mais clara
       */
      light?: string | null;
      /**
       * Variante mais escura
       */
      dark?: string | null;
      /**
       * Cor do texto sobre fundo secundário
       */
      contrast?: string | null;
    };
    accent?: {
      /**
       * Cor de destaque para ênfases e CTAs
       */
      main?: string | null;
      contrast?: string | null;
    };
    background: {
      /**
       * Cor de fundo padrão
       */
      default: string;
      /**
       * Fundo para cards e superfícies elevadas
       */
      paper?: string | null;
      /**
       * Fundo para cabeçalhos, barras de ferramentas
       */
      elevated?: string | null;
    };
    text: {
      /**
       * Cor de texto principal
       */
      primary: string;
      /**
       * Cor de texto secundária/suave
       */
      secondary?: string | null;
      /**
       * Cor de texto desabilitado
       */
      disabled?: string | null;
      /**
       * Cor de texto para dicas/placeholders
       */
      hint?: string | null;
    };
    semantic?: {
      /**
       * Cor de estado de sucesso
       */
      success?: string | null;
      /**
       * Cor de estado de erro
       */
      error?: string | null;
      /**
       * Cor de estado de aviso
       */
      warning?: string | null;
      /**
       * Cor de estado de informação
       */
      info?: string | null;
    };
    /**
     * Cor de borda e divisor
     */
    divider?: string | null;
  };
  typography?: {
    fontFamily?: {
      /**
       * Família de fonte principal para corpo de texto
       */
      primary?: string | null;
      /**
       * Família de fonte para cabeçalhos
       */
      heading?: string | null;
      /**
       * Fonte monoespaçada para blocos de código
       */
      monospace?: string | null;
    };
    fontSize?: {
      /**
       * Tamanho do Cabeçalho 1
       */
      h1?: number | null;
      h2?: number | null;
      h3?: number | null;
      h4?: number | null;
      h5?: number | null;
      h6?: number | null;
      /**
       * Tamanho base do corpo de texto
       */
      body?: number | null;
      /**
       * Tamanho de texto pequeno
       */
      small?: number | null;
      /**
       * Legenda e texto de ajuda
       */
      caption?: number | null;
    };
    fontWeight?: {
      light?: number | null;
      regular?: number | null;
      medium?: number | null;
      semibold?: number | null;
      bold?: number | null;
    };
    lineHeight?: {
      /**
       * Altura de linha justa para cabeçalhos
       */
      tight?: number | null;
      /**
       * Altura de linha normal para corpo de texto
       */
      normal?: number | null;
      /**
       * Altura de linha relaxada para legibilidade
       */
      relaxed?: number | null;
    };
  };
  /**
   * Defina unidades de espaçamento para margens e preenchimentos consistentes
   */
  spacing?: {
    /**
     * Extra pequeno (4px)
     */
    xs?: number | null;
    /**
     * Pequeno (8px)
     */
    sm?: number | null;
    /**
     * Médio (16px)
     */
    md?: number | null;
    /**
     * Grande (24px)
     */
    lg?: number | null;
    /**
     * Extra grande (32px)
     */
    xl?: number | null;
    /**
     * 2X grande (48px)
     */
    xxl?: number | null;
  };
  borderRadius?: {
    none?: number | null;
    sm?: number | null;
    md?: number | null;
    lg?: number | null;
    xl?: number | null;
    /**
     * Totalmente arredondado (forma de pílula)
     */
    full?: number | null;
  };
  shadows?: {
    /**
     * Sombra pequena (elevação sutil)
     */
    sm?: string | null;
    /**
     * Sombra média (cards)
     */
    md?: string | null;
    /**
     * Sombra grande (modais, popovers)
     */
    lg?: string | null;
    /**
     * Sombra extra grande (sobreposições)
     */
    xl?: string | null;
  };
  components?: {
    button?: {
      /**
       * Raio da borda do botão
       */
      borderRadius?: number | null;
      /**
       * Preenchimento horizontal
       */
      paddingX?: number | null;
      /**
       * Preenchimento vertical
       */
      paddingY?: number | null;
    };
    card?: {
      borderRadius?: number | null;
      padding?: number | null;
      shadow?: ('none' | 'sm' | 'md' | 'lg') | null;
    };
    input?: {
      borderRadius?: number | null;
      borderColor?: string | null;
      focusBorderColor?: string | null;
    };
  };
  /**
   * CSS personalizado adicional para injetar (apenas usuários avançados)
   */
  customCSS?: string | null;
  metadata?: {
    /**
     * Versão do tema para rastrear mudanças
     */
    version?: string | null;
    /**
     * Autor/criador do tema
     */
    author?: string | null;
    /**
     * Tags separadas por vírgula (ex: "escuro, minimalista, corporativo")
     */
    tags?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * User role determines access and permissions
   */
  role: 'admin' | 'editor' | 'reporter' | 'art_editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Nome da categoria (ex: "Esportes", "Tecnologia", "Cultura")
   */
  name: string;
  /**
   * Identificador amigável para URL
   */
  slug: string;
  /**
   * Cor para organização visual
   */
  color?: ('red' | 'orange' | 'yellow' | 'green' | 'blue' | 'purple' | 'brown' | 'gray') | null;
  /**
   * Descrição opcional (máx 200 caracteres)
   */
  description?: string | null;
  /**
   * Arraste e solte os artigos para definir a ordem de exibição nesta categoria.
   */
  articles?: (number | Article)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Dados de análise e rastreamento de desempenho de conteúdo e engajamento de usuários
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics".
 */
export interface Analytics {
  id: number;
  /**
   * Tipo de conteúdo que está sendo rastreado
   */
  contentType: 'article' | 'post' | 'media' | 'page';
  /**
   * ID do item de conteúdo (artigo, postagem, etc.)
   */
  contentId: string;
  /**
   * Título do conteúdo para referência
   */
  contentTitle?: string | null;
  /**
   * Tipo de evento analítico registrado
   */
  eventType: 'page_view' | 'content_read' | 'video_play' | 'video_complete' | 'share' | 'like' | 'comment' | 'download';
  /**
   * Identificador único do usuário (anônimo ou autenticado)
   */
  userId?: string | null;
  /**
   * Identificador da sessão para agrupar atividades do usuário
   */
  sessionId?: string | null;
  /**
   * Indica se o usuário estava logado
   */
  isAuthenticated?: boolean | null;
  deviceInfo?: {
    deviceType?: ('desktop' | 'mobile' | 'tablet' | 'other') | null;
    /**
     * Sistema operacional (ex: iOS, Android, Windows)
     */
    os?: string | null;
    osVersion?: string | null;
    /**
     * Nome do navegador (ex: Chrome, Safari, Firefox)
     */
    browser?: string | null;
    browserVersion?: string | null;
    /**
     * Resolução da tela (ex: 1920x1080)
     */
    screenResolution?: string | null;
  };
  geoLocation?: {
    country?: string | null;
    /**
     * Código ISO do país (ex: BR, US, UK)
     */
    countryCode?: string | null;
    /**
     * Estado ou região
     */
    region?: string | null;
    city?: string | null;
    latitude?: number | null;
    longitude?: number | null;
  };
  engagementMetrics?: {
    /**
     * Tempo gasto no conteúdo (em segundos)
     */
    timeSpent?: number | null;
    /**
     * Percentual de rolagem do conteúdo (0–100)
     */
    scrollDepth?: number | null;
    /**
     * Número de cliques/interações
     */
    clickCount?: number | null;
    /**
     * Usuário saiu sem interação
     */
    bounced?: boolean | null;
  };
  trafficSource?: {
    /**
     * URL de referência
     */
    referrer?: string | null;
    source?: ('direct' | 'search' | 'social' | 'email' | 'referral' | 'other') | null;
    /**
     * Meio de marketing (ex: cpc, orgânico, e-mail)
     */
    medium?: string | null;
    /**
     * Nome da campanha para rastreamento
     */
    campaign?: string | null;
    /**
     * Parâmetros UTM completos em formato JSON
     */
    utmParams?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Endereço IP do usuário (anonimizado por privacidade)
   */
  ipAddress?: string | null;
  /**
   * String completa do agente do usuário
   */
  userAgent?: string | null;
  /**
   * Metadados adicionais personalizados em formato JSON
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reels".
 */
export interface Reel {
  id: number;
  title: string;
  url: string;
  platform: 'tiktok' | 'reels' | 'youtube';
  embedHtml?: string | null;
  thumbnailUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'themes';
        value: number | Theme;
      } | null)
    | ({
        relationTo: 'analytics';
        value: number | Analytics;
      } | null)
    | ({
        relationTo: 'reels';
        value: number | Reel;
      } | null)
    | ({
        relationTo: 'payload-kv';
        value: number | PayloadKv;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  slug?: T;
  cardType?: T;
  theme?: T;
  featured?: T;
  featuredImage?: T;
  description?: T;
  authors?: T;
  categories?: T;
  status?: T;
  publishedAt?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  color?: T;
  description?: T;
  articles?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes_select".
 */
export interface ThemesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  isActive?: T;
  isDefault?: T;
  colors?:
    | T
    | {
        primary?:
          | T
          | {
              main?: T;
              light?: T;
              dark?: T;
              contrast?: T;
            };
        secondary?:
          | T
          | {
              main?: T;
              light?: T;
              dark?: T;
              contrast?: T;
            };
        accent?:
          | T
          | {
              main?: T;
              contrast?: T;
            };
        background?:
          | T
          | {
              default?: T;
              paper?: T;
              elevated?: T;
            };
        text?:
          | T
          | {
              primary?: T;
              secondary?: T;
              disabled?: T;
              hint?: T;
            };
        semantic?:
          | T
          | {
              success?: T;
              error?: T;
              warning?: T;
              info?: T;
            };
        divider?: T;
      };
  typography?:
    | T
    | {
        fontFamily?:
          | T
          | {
              primary?: T;
              heading?: T;
              monospace?: T;
            };
        fontSize?:
          | T
          | {
              h1?: T;
              h2?: T;
              h3?: T;
              h4?: T;
              h5?: T;
              h6?: T;
              body?: T;
              small?: T;
              caption?: T;
            };
        fontWeight?:
          | T
          | {
              light?: T;
              regular?: T;
              medium?: T;
              semibold?: T;
              bold?: T;
            };
        lineHeight?:
          | T
          | {
              tight?: T;
              normal?: T;
              relaxed?: T;
            };
      };
  spacing?:
    | T
    | {
        xs?: T;
        sm?: T;
        md?: T;
        lg?: T;
        xl?: T;
        xxl?: T;
      };
  borderRadius?:
    | T
    | {
        none?: T;
        sm?: T;
        md?: T;
        lg?: T;
        xl?: T;
        full?: T;
      };
  shadows?:
    | T
    | {
        sm?: T;
        md?: T;
        lg?: T;
        xl?: T;
      };
  components?:
    | T
    | {
        button?:
          | T
          | {
              borderRadius?: T;
              paddingX?: T;
              paddingY?: T;
            };
        card?:
          | T
          | {
              borderRadius?: T;
              padding?: T;
              shadow?: T;
            };
        input?:
          | T
          | {
              borderRadius?: T;
              borderColor?: T;
              focusBorderColor?: T;
            };
      };
  customCSS?: T;
  metadata?:
    | T
    | {
        version?: T;
        author?: T;
        tags?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics_select".
 */
export interface AnalyticsSelect<T extends boolean = true> {
  contentType?: T;
  contentId?: T;
  contentTitle?: T;
  eventType?: T;
  userId?: T;
  sessionId?: T;
  isAuthenticated?: T;
  deviceInfo?:
    | T
    | {
        deviceType?: T;
        os?: T;
        osVersion?: T;
        browser?: T;
        browserVersion?: T;
        screenResolution?: T;
      };
  geoLocation?:
    | T
    | {
        country?: T;
        countryCode?: T;
        region?: T;
        city?: T;
        latitude?: T;
        longitude?: T;
      };
  engagementMetrics?:
    | T
    | {
        timeSpent?: T;
        scrollDepth?: T;
        clickCount?: T;
        bounced?: T;
      };
  trafficSource?:
    | T
    | {
        referrer?: T;
        source?: T;
        medium?: T;
        campaign?: T;
        utmParams?: T;
      };
  ipAddress?: T;
  userAgent?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reels_select".
 */
export interface ReelsSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  platform?: T;
  embedHtml?: T;
  thumbnailUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-layout".
 */
export interface AppLayout {
  id: number;
  sections?:
    | (
        | {
            featureType?: ('article' | 'video') | null;
            article?: (number | null) | Article;
            videoFeature?: {
              videoUrl: string;
              isLive?: boolean | null;
            };
            isHidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featured-article';
          }
        | {
            category: number | Category;
            isHidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'category-section';
          }
        | {
            title: string;
            reels?: (number | Reel)[] | null;
            isHidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'reels-section';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-layout_select".
 */
export interface AppLayoutSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        'featured-article'?:
          | T
          | {
              featureType?: T;
              article?: T;
              videoFeature?:
                | T
                | {
                    videoUrl?: T;
                    isLive?: T;
                  };
              isHidden?: T;
              id?: T;
              blockName?: T;
            };
        'category-section'?:
          | T
          | {
              category?: T;
              isHidden?: T;
              id?: T;
              blockName?: T;
            };
        'reels-section'?:
          | T
          | {
              title?: T;
              reels?: T;
              isHidden?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}