/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    articles: Article;
    categories: Category;
    media: Media;
    users: User;
    themes: Theme;
    analytics: Analytics;
    reels: Reel;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    themes: ThemesSelect<false> | ThemesSelect<true>;
    analytics: AnalyticsSelect<false> | AnalyticsSelect<true>;
    reels: ReelsSelect<false> | ReelsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'app-layout': AppLayout;
  };
  globalsSelect: {
    'app-layout': AppLayoutSelect<false> | AppLayoutSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  /**
   * Article title (max 200 characters)
   */
  title: string;
  content: {
    [k: string]: unknown;
  }[];
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Como este artigo deve aparecer nas listagens.
   */
  cardType: 'card_normal' | 'card_detailed' | 'title_only' | 'thumbnail_only';
  /**
   * Select a theme for this article
   */
  theme?: (number | null) | Theme;
  /**
   * Mark as featured article (appears on top)
   */
  featured?: boolean | null;
  /**
   * Main featured image for the article
   */
  featuredImage?: (number | null) | Media;
  /**
   * Short description for previews (max 300 characters)
   */
  description?: string | null;
  /**
   * Select article authors (multiple selection allowed)
   */
  authors?: (number | User)[] | null;
  /**
   * Select categories for this article
   */
  categories?: (number | Category)[] | null;
  /**
   * Current publication status
   */
  status: 'draft' | 'pending_approval' | 'published' | 'rejected';
  /**
   * Publication date
   */
  publishedAt?: string | null;
  /**
   * Article creator
   */
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage application themes, colors, typography, and visual styling
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes".
 */
export interface Theme {
  id: number;
  /**
   * Theme name (e.g., "Campus Default", "Dark Mode", "High Contrast")
   */
  name: string;
  /**
   * URL-friendly identifier for API access
   */
  slug: string;
  /**
   * Description of this theme and when to use it
   */
  description?: string | null;
  /**
   * Enable/disable this theme
   */
  isActive?: boolean | null;
  /**
   * Set as default theme (only one should be default)
   */
  isDefault?: boolean | null;
  colors: {
    primary: {
      /**
       * Primary brand color (hex format: #1976d2)
       */
      main: string;
      /**
       * Lighter variant (auto-generated if empty)
       */
      light?: string | null;
      /**
       * Darker variant (auto-generated if empty)
       */
      dark?: string | null;
      /**
       * Text color on primary background
       */
      contrast?: string | null;
    };
    secondary: {
      /**
       * Secondary brand color
       */
      main: string;
      /**
       * Lighter variant
       */
      light?: string | null;
      /**
       * Darker variant
       */
      dark?: string | null;
      /**
       * Text color on secondary background
       */
      contrast?: string | null;
    };
    accent?: {
      /**
       * Accent color for highlights and CTAs
       */
      main?: string | null;
      contrast?: string | null;
    };
    background: {
      /**
       * Default background color
       */
      default: string;
      /**
       * Background for cards and elevated surfaces
       */
      paper?: string | null;
      /**
       * Background for headers, toolbars
       */
      elevated?: string | null;
    };
    text: {
      /**
       * Primary text color
       */
      primary: string;
      /**
       * Secondary/muted text color
       */
      secondary?: string | null;
      /**
       * Disabled text color
       */
      disabled?: string | null;
      /**
       * Hint/placeholder text color
       */
      hint?: string | null;
    };
    semantic?: {
      /**
       * Success state color
       */
      success?: string | null;
      /**
       * Error state color
       */
      error?: string | null;
      /**
       * Warning state color
       */
      warning?: string | null;
      /**
       * Info state color
       */
      info?: string | null;
    };
    /**
     * Border and divider color
     */
    divider?: string | null;
  };
  typography?: {
    fontFamily?: {
      /**
       * Primary font family for body text
       */
      primary?: string | null;
      /**
       * Font family for headings
       */
      heading?: string | null;
      /**
       * Monospace font for code blocks
       */
      monospace?: string | null;
    };
    fontSize?: {
      /**
       * Heading 1 size
       */
      h1?: number | null;
      h2?: number | null;
      h3?: number | null;
      h4?: number | null;
      h5?: number | null;
      h6?: number | null;
      /**
       * Base body text size
       */
      body?: number | null;
      /**
       * Small text size
       */
      small?: number | null;
      /**
       * Caption and helper text
       */
      caption?: number | null;
    };
    fontWeight?: {
      light?: number | null;
      regular?: number | null;
      medium?: number | null;
      semibold?: number | null;
      bold?: number | null;
    };
    lineHeight?: {
      /**
       * Tight line height for headings
       */
      tight?: number | null;
      /**
       * Normal line height for body text
       */
      normal?: number | null;
      /**
       * Relaxed line height for readability
       */
      relaxed?: number | null;
    };
  };
  /**
   * Define spacing units for consistent margins and padding
   */
  spacing?: {
    /**
     * Extra small (4px)
     */
    xs?: number | null;
    /**
     * Small (8px)
     */
    sm?: number | null;
    /**
     * Medium (16px)
     */
    md?: number | null;
    /**
     * Large (24px)
     */
    lg?: number | null;
    /**
     * Extra large (32px)
     */
    xl?: number | null;
    /**
     * 2X large (48px)
     */
    xxl?: number | null;
  };
  borderRadius?: {
    none?: number | null;
    sm?: number | null;
    md?: number | null;
    lg?: number | null;
    xl?: number | null;
    /**
     * Fully rounded (pill shape)
     */
    full?: number | null;
  };
  shadows?: {
    /**
     * Small shadow (subtle elevation)
     */
    sm?: string | null;
    /**
     * Medium shadow (cards)
     */
    md?: string | null;
    /**
     * Large shadow (modals, popovers)
     */
    lg?: string | null;
    /**
     * Extra large shadow (overlays)
     */
    xl?: string | null;
  };
  components?: {
    button?: {
      /**
       * Button border radius
       */
      borderRadius?: number | null;
      /**
       * Horizontal padding
       */
      paddingX?: number | null;
      /**
       * Vertical padding
       */
      paddingY?: number | null;
    };
    card?: {
      borderRadius?: number | null;
      padding?: number | null;
      shadow?: ('none' | 'sm' | 'md' | 'lg') | null;
    };
    input?: {
      borderRadius?: number | null;
      borderColor?: string | null;
      focusBorderColor?: string | null;
    };
  };
  /**
   * Additional custom CSS to inject (advanced users only)
   */
  customCSS?: string | null;
  metadata?: {
    /**
     * Theme version for tracking changes
     */
    version?: string | null;
    /**
     * Theme author/creator
     */
    author?: string | null;
    /**
     * Comma-separated tags (e.g., "dark, minimal, corporate")
     */
    tags?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * User role determines access and permissions
   */
  role: 'admin' | 'editor' | 'reporter' | 'art_editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Category name (e.g., "Sports", "Technology", "Culture")
   */
  name: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Color for visual organization
   */
  color?: ('red' | 'orange' | 'yellow' | 'green' | 'blue' | 'purple' | 'brown' | 'gray') | null;
  /**
   * Optional description (max 200 characters)
   */
  description?: string | null;
  /**
   * Arraste e solte os artigos para definir a ordem de exibição nesta categoria.
   */
  articles?: (number | Article)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Analytics and tracking data for content performance and user engagement
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics".
 */
export interface Analytics {
  id: number;
  /**
   * Type of content being tracked
   */
  contentType: 'article' | 'post' | 'media' | 'page';
  /**
   * ID of the content item (article, post, etc.)
   */
  contentId: string;
  /**
   * Title of the content for easier reference
   */
  contentTitle?: string | null;
  /**
   * Type of analytics event
   */
  eventType: 'page_view' | 'content_read' | 'video_play' | 'video_complete' | 'share' | 'like' | 'comment' | 'download';
  /**
   * Unique user identifier (anonymous or authenticated)
   */
  userId?: string | null;
  /**
   * Session identifier for grouping user activity
   */
  sessionId?: string | null;
  /**
   * Whether the user was logged in
   */
  isAuthenticated?: boolean | null;
  deviceInfo?: {
    deviceType?: ('desktop' | 'mobile' | 'tablet' | 'other') | null;
    /**
     * Operating system (e.g., iOS, Android, Windows)
     */
    os?: string | null;
    osVersion?: string | null;
    /**
     * Browser name (e.g., Chrome, Safari, Firefox)
     */
    browser?: string | null;
    browserVersion?: string | null;
    /**
     * Screen resolution (e.g., 1920x1080)
     */
    screenResolution?: string | null;
  };
  geoLocation?: {
    country?: string | null;
    /**
     * ISO country code (e.g., US, BR, UK)
     */
    countryCode?: string | null;
    /**
     * State or region
     */
    region?: string | null;
    city?: string | null;
    latitude?: number | null;
    longitude?: number | null;
  };
  engagementMetrics?: {
    /**
     * Time spent on content in seconds
     */
    timeSpent?: number | null;
    /**
     * Percentage of content scrolled (0-100)
     */
    scrollDepth?: number | null;
    /**
     * Number of clicks/interactions
     */
    clickCount?: number | null;
    /**
     * User left without interaction
     */
    bounced?: boolean | null;
  };
  trafficSource?: {
    /**
     * Referring URL
     */
    referrer?: string | null;
    source?: ('direct' | 'search' | 'social' | 'email' | 'referral' | 'other') | null;
    /**
     * Marketing medium (e.g., cpc, organic, email)
     */
    medium?: string | null;
    /**
     * Campaign name for tracking
     */
    campaign?: string | null;
    /**
     * Full UTM parameters as JSON
     */
    utmParams?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * User IP address (anonymized for privacy)
   */
  ipAddress?: string | null;
  /**
   * Full user agent string
   */
  userAgent?: string | null;
  /**
   * Additional custom metadata as JSON
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reels".
 */
export interface Reel {
  id: number;
  title: string;
  url: string;
  platform: 'tiktok' | 'reels';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'themes';
        value: number | Theme;
      } | null)
    | ({
        relationTo: 'analytics';
        value: number | Analytics;
      } | null)
    | ({
        relationTo: 'reels';
        value: number | Reel;
      } | null)
    | ({
        relationTo: 'payload-kv';
        value: number | PayloadKv;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  slug?: T;
  cardType?: T;
  theme?: T;
  featured?: T;
  featuredImage?: T;
  description?: T;
  authors?: T;
  categories?: T;
  status?: T;
  publishedAt?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  color?: T;
  description?: T;
  articles?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes_select".
 */
export interface ThemesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  isActive?: T;
  isDefault?: T;
  colors?:
    | T
    | {
        primary?:
          | T
          | {
              main?: T;
              light?: T;
              dark?: T;
              contrast?: T;
            };
        secondary?:
          | T
          | {
              main?: T;
              light?: T;
              dark?: T;
              contrast?: T;
            };
        accent?:
          | T
          | {
              main?: T;
              contrast?: T;
            };
        background?:
          | T
          | {
              default?: T;
              paper?: T;
              elevated?: T;
            };
        text?:
          | T
          | {
              primary?: T;
              secondary?: T;
              disabled?: T;
              hint?: T;
            };
        semantic?:
          | T
          | {
              success?: T;
              error?: T;
              warning?: T;
              info?: T;
            };
        divider?: T;
      };
  typography?:
    | T
    | {
        fontFamily?:
          | T
          | {
              primary?: T;
              heading?: T;
              monospace?: T;
            };
        fontSize?:
          | T
          | {
              h1?: T;
              h2?: T;
              h3?: T;
              h4?: T;
              h5?: T;
              h6?: T;
              body?: T;
              small?: T;
              caption?: T;
            };
        fontWeight?:
          | T
          | {
              light?: T;
              regular?: T;
              medium?: T;
              semibold?: T;
              bold?: T;
            };
        lineHeight?:
          | T
          | {
              tight?: T;
              normal?: T;
              relaxed?: T;
            };
      };
  spacing?:
    | T
    | {
        xs?: T;
        sm?: T;
        md?: T;
        lg?: T;
        xl?: T;
        xxl?: T;
      };
  borderRadius?:
    | T
    | {
        none?: T;
        sm?: T;
        md?: T;
        lg?: T;
        xl?: T;
        full?: T;
      };
  shadows?:
    | T
    | {
        sm?: T;
        md?: T;
        lg?: T;
        xl?: T;
      };
  components?:
    | T
    | {
        button?:
          | T
          | {
              borderRadius?: T;
              paddingX?: T;
              paddingY?: T;
            };
        card?:
          | T
          | {
              borderRadius?: T;
              padding?: T;
              shadow?: T;
            };
        input?:
          | T
          | {
              borderRadius?: T;
              borderColor?: T;
              focusBorderColor?: T;
            };
      };
  customCSS?: T;
  metadata?:
    | T
    | {
        version?: T;
        author?: T;
        tags?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics_select".
 */
export interface AnalyticsSelect<T extends boolean = true> {
  contentType?: T;
  contentId?: T;
  contentTitle?: T;
  eventType?: T;
  userId?: T;
  sessionId?: T;
  isAuthenticated?: T;
  deviceInfo?:
    | T
    | {
        deviceType?: T;
        os?: T;
        osVersion?: T;
        browser?: T;
        browserVersion?: T;
        screenResolution?: T;
      };
  geoLocation?:
    | T
    | {
        country?: T;
        countryCode?: T;
        region?: T;
        city?: T;
        latitude?: T;
        longitude?: T;
      };
  engagementMetrics?:
    | T
    | {
        timeSpent?: T;
        scrollDepth?: T;
        clickCount?: T;
        bounced?: T;
      };
  trafficSource?:
    | T
    | {
        referrer?: T;
        source?: T;
        medium?: T;
        campaign?: T;
        utmParams?: T;
      };
  ipAddress?: T;
  userAgent?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reels_select".
 */
export interface ReelsSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  platform?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-layout".
 */
export interface AppLayout {
  id: number;
  sections?:
    | (
        | {
            article: number | Article;
            isHidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featured-article';
          }
        | {
            category: number | Category;
            isHidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'category-section';
          }
        | {
            title: string;
            reels?: (number | Reel)[] | null;
            isHidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'reels-section';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-layout_select".
 */
export interface AppLayoutSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        'featured-article'?:
          | T
          | {
              article?: T;
              isHidden?: T;
              id?: T;
              blockName?: T;
            };
        'category-section'?:
          | T
          | {
              category?: T;
              isHidden?: T;
              id?: T;
              blockName?: T;
            };
        'reels-section'?:
          | T
          | {
              title?: T;
              reels?: T;
              isHidden?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}